### ISSUE TITLE
Plugin crashing after latest update

### ISSUE THREAD

**Issue by HughMungis** [Goldenfreddy0703/Otaku#100]
I tried uninstalling and reinstalling. I'm on Kodi v18.9 (leah) and LibreElec 9.2.8. It was working fine this morning and now... he's dead jim!

I rebooted and ONLY started Otaku to get fresh logs. The relevant error is below.

```
2023-03-09 18:36:42.179 T:1499452288   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: invalid syntax (control.py, line 464)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.otaku/default.py", line 19, in <module>
                                                from resources.lib import main
                                              File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 21, in <module>
                                                from resources.lib.AniListBrowser import AniListBrowser
                                              File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/AniListBrowser.py", line 13, in <module>
                                                from resources.lib.ui import client, control, database, get_meta, utils
                                              File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/ui/client.py", line 30, in <module>
                                                from resources.lib.ui import control, database
                                              File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/ui/control.py", line 464
                                                def print(string, *args):
                                                        ^
                                            SyntaxError: invalid syntax
                                            -->End of Python script error report<--
2023-03-09 18:36:42.213 T:1887429504   ERROR: GetDirectory - Error getting plugin://plugin.video.otaku/
2023-03-09 18:36:42.215 T:1937207360   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/) failed
```

**Comment by joezito129** [comment]
comment out lines 465-469 of control.py and that should fix it

**Comment by Goldenfreddy0703** [comment]
Hey sorry i never replied but recently we made a release, hopefully lines 465-469 should be removed in this release. 
Btw you may want to consider trying kodi 19 or 20. its fast and Otaku functions better on it. 
Anyway im going to close this but big thanks to @joezito129 for finding the errors and fixing this.
