### ISSUE TITLE
Not able to get some Chinese Anime

### ISSUE THREAD

**Issue by tunafish90** [Goldenfreddy0703/Otaku#192]
When searching for some Chinese anime on Otaku, it does not show up, yet when I search on AniList, I can find it. 

I am not sure why this is happening since you say you pull from AniLIst in terms of listing.

Here are some of the anime I have tried searching for (Note: I have tried variations of the English translation as well):
- https://anilist.co/anime/102464/Dou-Po-Cangqiong/
- https://anilist.co/anime/117012/Tunshi-Xingkong/

Software: 
Kodi 20+
Otaku (Latest version on repo)

Hardware:
ChromeCast

**Comment by zambux** [comment]
same 
but whit 2 Chinese and 1 japonese 

https://anilist.co/anime/141881/Kao-Ni-La-Zhanshen-Xitong-/
https://anilist.co/anime/114959/Yaojing-Zhongzhi-Shouce/

https://anilist.co/anime/97907/Death-March-Kara-Hajimaru-Isekai-Kyousoukyoku/
log
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.otaku/default.py", line 21, in <module>
                                                       main.Main()
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2526, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/WatchlistIntegration.py", line 67, in WATCHLIST_TO_EP
                                                       anime_general, content_type = OtakuBrowser().get_anime_init(anilist_id)
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/OtakuBrowser.py", line 109, in get_anime_init
                                                       data = simkl.SIMKLAPI().get_episodes(anilist_id, filter_lang)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 174, in get_episodes
                                                       return self._process_episode_view(anilist_id, poster, fanart, eps_watched, tvshowtitle, filter_lang,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 107, in _process_episode_view
                                                       all_results = list(map(mapfunc, result_ep))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 44, in _parse_episode_view
                                                       show_art = pickle.loads(show_meta.get('art')) if show_meta.get('art') else {}
                                                                                                        ^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2023-12-29 14:24:58.224 T:128168   error <general>: GetDirectory - Error getting plugin://plugin.video.otaku/watchlist_to_ep/97907/34497//12
2023-12-29 14:24:58.247 T:127763   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/watchlist_to_ep/97907/34497//12) failed

2023-12-29 14:31:58.495 T:128725   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.otaku/default.py", line 21, in <module>
                                                       main.Main()
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2526, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/WatchlistIntegration.py", line 67, in WATCHLIST_TO_EP
                                                       anime_general, content_type = OtakuBrowser().get_anime_init(anilist_id)
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/OtakuBrowser.py", line 109, in get_anime_init
                                                       data = simkl.SIMKLAPI().get_episodes(anilist_id, filter_lang)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 174, in get_episodes
                                                       return self._process_episode_view(anilist_id, poster, fanart, eps_watched, tvshowtitle, filter_lang,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 107, in _process_episode_view
                                                       all_results = list(map(mapfunc, result_ep))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 44, in _parse_episode_view
                                                       show_art = pickle.loads(show_meta.get('art')) if show_meta.get('art') else {}
                                                                                                        ^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2023-12-29 14:31:58.816 T:128724   error <general>: GetDirectory - Error getting plugin://plugin.video.otaku/watchlist_to_ep/114959/41093//14
2023-12-29 14:31:58.846 T:127763   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/watchlist_to_ep/114959/41093//14) failed

2023-12-29 14:34:58.018 T:128862   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.otaku/default.py", line 21, in <module>
                                                       main.Main()
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2526, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/WatchlistIntegration.py", line 67, in WATCHLIST_TO_EP
                                                       anime_general, content_type = OtakuBrowser().get_anime_init(anilist_id)
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/OtakuBrowser.py", line 109, in get_anime_init
                                                       data = simkl.SIMKLAPI().get_episodes(anilist_id, filter_lang)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 174, in get_episodes
                                                       return self._process_episode_view(anilist_id, poster, fanart, eps_watched, tvshowtitle, filter_lang,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 107, in _process_episode_view
                                                       all_results = list(map(mapfunc, result_ep))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 44, in _parse_episode_view
                                                       show_art = pickle.loads(show_meta.get('art')) if show_meta.get('art') else {}
                                                                                                        ^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2023-12-29 14:34:58.392 T:128861   error <general>: GetDirectory - Error getting plugin://plugin.video.otaku/watchlist_to_ep/141881/52178//16
2023-12-29 14:34:58.424 T:127763   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/watchlist_to_ep/141881/52178//16) failed

**Comment by Goldenfreddy0703** [comment]
Hey there, sorry i never got back to you. Ok so about all the Chinese Anime, reason why you guys are getting these errors is cause there is no episode meta for them unfortunately and without episode meta, you can't really play these and also, these are ona animes and i don't think simkl supports that. We get are episode meta from simkl so thats probably why you guys are gettings errors for Chinese Anime. 

About the Japanese Anime "Death March Kara Hajimaru Isekai Kyousoukyoku", i was able to get episode meta and streams just fine with it. 

Episode Meta:
![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/09e80cf7-acd4-43c8-b733-9dd0a8f0ea47)

Streams: 
![image](https://github.com/Goldenfreddy0703/Otaku/assets/62456796/fb5db92c-0fea-4cb9-96d9-e13b02c213a7)

But yeah sorry for the people who watch Chinese Anime, They can be hard to get these days,

**Comment by tunafish90** [comment]
Thank you for the response!

Can you clarify what you mean by episode meta and how that pertains to searching for anime on Otaku?

I am wondering because I know that those Chinese anime exist on GoGoAnime and you list GoGo as a provider in the settings.

**Comment by Goldenfreddy0703** [comment]
Ok so episode meta is basically when you open an anime, it would show episode thumbnails, plots, titles, airdates, ect so when you open an anime, it would load up episode meta.

**Comment by tunafish90** [comment]
That's what I thought, but wasn't wanting to assume, ty!

Since it exists on simkl but doesn't have full episode metadata, would it be possible to put placeholder information for key episode meta information so that it can still be pulled from a provider to be watched (assuming the supplied name is correct)?

**Comment by Goldenfreddy0703** [comment]
Sadly not really but wait, you said it exist on simkl, mind giving me those links so I could review them?

**Comment by tunafish90** [comment]
That's a bummer.

Yeah, here are the links:
- https://simkl.com/anime/1972214/dou-po-cangqiong-nian-fan
- https://simkl.com/anime/2333760/tunshi-xingkong-4

**Comment by Goldenfreddy0703** [comment]
> That's a bummer.
> 
> Yeah, here are the links:
> - https://simkl.com/anime/1972214/dou-po-cangqiong-nian-fan
> - https://simkl.com/anime/2333760/tunshi-xingkong-4

Ok odd. They have episodes but just no thumbnail which is normal. I thought simkl did not have these, my bad. @Gujal00 sorry to bother you but would you mind looking into this?

**Comment by zambux** [comment]
I check and The Chinese Ones i tolde hare in simkl.com to, The japoneses One a clear The metadata off The adon anda now is ok.

**Comment by zambux** [comment]
Any news

**Comment by Goldenfreddy0703** [comment]
Oh I completely forgot about this, sorry about that 😅

Will need to look into it.

**Comment by Goldenfreddy0703** [comment]
Tell you what, let me open this issue back up sense it needs investigating cause these Chinese shows are on simkl so we should have gotten episode meta from them.

**Comment by zambux** [comment]
Thanks

**Comment by Goldenfreddy0703** [comment]
Hey good news, apparently we did find a few small bugs with a few of these animes so thank you very much, we will make a release in a few min so im going to go ahead and close this issue. if you guys have any questions or concerns about this issues, pls feel free to reply back in here and we will open it up and look further into this. 
Thank you

Huge thanks to @Gujal00 for fixing the episode meta and the resolving.
