### ISSUE TITLE
Otaku Next Up not getting update with new next episode 

### ISSUE THREAD

**Issue by minhgi** [Goldenfreddy0703/Otaku#198]
Kodi 20.3
Latest otaku addon.
Watch list service used:  MyAnimeList

Found this error: 

2024-01-14 12:10:46.276 T:32148   error <general>: 
2024-01-14 12:10:46.278 T:32148   error <general>:   File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/database.py", line 50, in get
                                                       fresh_result = repr(function(*args, **kwargs))
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-01-14 12:10:46.278 T:32148   error <general>: 
2024-01-14 12:10:46.278 T:32148   error <general>:   File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/AniListBrowser.py", line 3830, in get_base_res
                                                       results = json.loads(result)
                                                                 ^^^^^^^^^^^^^^^^^^
                                                   
2024-01-14 12:10:46.278 T:32148   error <general>: 
2024-01-14 12:10:46.278 T:32148   error <general>:   File "/data/user/0/net.kodinerds.maven.kodi20/cache/apk/assets/python3.11/lib/python3.11/json/__init__.py", line 346, in loads
                                                       return _default_decoder.decode(s)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-01-14 12:10:46.278 T:32148   error <general>: 
2024-01-14 12:10:46.279 T:32148   error <general>:   File "/data/user/0/net.kodinerds.maven.kodi20/cache/apk/assets/python3.11/lib/python3.11/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-01-14 12:10:46.279 T:32148   error <general>: 
2024-01-14 12:10:46.279 T:32148   error <general>:   File "/data/user/0/net.kodinerds.maven.kodi20/cache/apk/assets/python3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   
2024-01-14 12:10:46.279 T:32148   error <general>: 
2024-01-14 12:10:46.279 T:32148   error <general>: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
2024-01-14 12:10:46.279 T:32148   error <general>: 
2024-01-14 12:10:46.300 T:32148   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/default.py", line 21, in <module>
                                                       main.Main()
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2526, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 1551, in ANILIST_AIRING_ANIME
                                                       return control.draw_items(_ANILIST_BROWSER.get_airing_anime())
                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/AniListBrowser.py", line 147, in get_airing_anime
                                                       return self._process_anilist_view(airing, "anilist_airing_anime/%d", page)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/divide_flavors.py", line 13, in wrapper
                                                       return f(*args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.otaku/resources/lib/AniListBrowser.py", line 4334, in _process_anilist_view
                                                       hasNextPage = json_res['pageInfo']['hasNextPage']
                                                                     ~~~~~~~~^^^^^^^^^^^^
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2024-01-14 12:10:46.499 T:32146   error <general>: GetDirectory - Error getting plugin://plugin.video.otaku/anilist_airing_anime?reload=

**Comment by Gujal00** [comment]
> Latest otaku addon.

Means nothing. what is the version?

Anyway the log snippets are useless would need full debug log. from the above snippet all one can say is that anilist api responded with a blank page at that time, may have been busy or whatever

**Comment by minhgi** [comment]
it's version 0.4.61
attaching the whole log.

[kodi.old.log](https://github.com/Goldenfreddy0703/Otaku/files/13952241/kodi.old.log)

**Comment by Goldenfreddy0703** [comment]
Hey so from viewing this log, turns out it seems you have a bunch of errors from other addons as well as ours and reason why is cause your using a modified build from Maven's Kodi-Builds für Android. We highly suggest you do a fresh install on a normal kodi build and download your favorite addons from there. We do not work with Maven's Kodi-Builds due to how modified they are. 

We are going to close this but if you have any questions or concerns about this, please feel free to reply in here and we will answer any question in here.
