### ISSUE TITLE
0.2.12 Issue scraping movies

### ISSUE THREAD

**Issue by meesterexx** [Goldenfreddy0703/Otaku#20]
First, a big thank you, amazing job on this addon! The latest update has really tightened things up. The only issue I've run into so far is scraping movies. I was testing in the All Time Popular and it throws errors for Your Name / Kimi No Na Wa and A Silent Voice / Koe No Katachi. Looking at the log, right before the scrape I can see it complaining about the nyaa_worker and some get sources, it then throws an exception on scrape. Below is the section from the log. This was done on Estuary to rule out skin any issues:

2022-10-07 09:56:20.610 T:2288     INFO <general>: Loading skin file: C:\K19portable\portable_data\addons\plugin.video.otaku\resources\skins\Default\1080i\get_sources.xml, load type: LOAD_ON_GUI_INIT
2022-10-07 09:56:21.116 T:4444    ERROR <general>: Exception in thread 
2022-10-07 09:56:21.116 T:4444    ERROR <general>: Thread-2
2022-10-07 09:56:21.116 T:4444    ERROR <general>: :
                                                   
2022-10-07 09:56:21.116 T:4444    ERROR <general>: Traceback (most recent call last):
                                                   
2022-10-07 09:56:21.116 T:4444    ERROR <general>:   File "C:\K19portable\system\python\Lib\threading.py", line 932, in _bootstrap_inner
                                                   
2022-10-07 09:56:21.116 T:4444    ERROR <general>:     
2022-10-07 09:56:21.117 T:4444    ERROR <general>: self.run()
2022-10-07 09:56:21.117 T:4444    ERROR <general>: 
                                                   
2022-10-07 09:56:21.117 T:4444    ERROR <general>:   File "C:\K19portable\system\python\Lib\threading.py", line 870, in run
                                                   
2022-10-07 09:56:21.117 T:4444    ERROR <general>:     
2022-10-07 09:56:21.117 T:4444    ERROR <general>: self._target(*self._args, **self._kwargs)
2022-10-07 09:56:21.117 T:4444    ERROR <general>: 
                                                   
2022-10-07 09:56:21.117 T:4444    ERROR <general>:   File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\pages\__init__.py", line 148, in nyaa_worker
                                                   
2022-10-07 09:56:21.117 T:4444    ERROR <general>:     
2022-10-07 09:56:21.117 T:4444    ERROR <general>: self.nyaaSources = nyaa.sources().get_sources(query, anilist_id, episode, status, media_type, rescrape)
2022-10-07 09:56:21.117 T:4444    ERROR <general>: 
                                                   
2022-10-07 09:56:21.117 T:4444    ERROR <general>:   File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\pages\nyaa.py", line 261, in get_sources
                                                   
2022-10-07 09:56:21.117 T:4444    ERROR <general>:     
2022-10-07 09:56:21.117 T:4444    ERROR <general>: return self._get_movie_sources(query, anilist_id, episode)
2022-10-07 09:56:21.117 T:4444    ERROR <general>: 
                                                   
2022-10-07 09:56:21.118 T:4444    ERROR <general>:   File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\pages\nyaa.py", line 368, in _get_movie_sources
                                                   
2022-10-07 09:56:21.118 T:4444    ERROR <general>:     
2022-10-07 09:56:21.118 T:4444    ERROR <general>: sources = self._get_movie_sources_backup(anilist_id)
2022-10-07 09:56:21.118 T:4444    ERROR <general>: 
                                                   
2022-10-07 09:56:21.118 T:4444    ERROR <general>:   File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\pages\nyaa.py", line 379, in _get_movie_sources_backup
                                                   
2022-10-07 09:56:21.118 T:4444    ERROR <general>:     
2022-10-07 09:56:21.118 T:4444    ERROR <general>: if 'general_title' in show:
2022-10-07 09:56:21.118 T:4444    ERROR <general>: 
                                                   
2022-10-07 09:56:21.118 T:4444    ERROR <general>: TypeError
2022-10-07 09:56:21.118 T:4444    ERROR <general>: : 
2022-10-07 09:56:21.118 T:4444    ERROR <general>: argument of type 'NoneType' is not iterable
2022-10-07 09:56:21.118 T:4444    ERROR <general>: 
                                                   
2022-10-07 09:57:20.869 T:9948    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\default.py", line 469, in <module>
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\ui\router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\default.py", line 360, in PLAY_MOVIE
                                                       link = SourceSelect(*('source_select.xml', control.ADDON_PATH),
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\windows\source_select.py", line 26, in __init__
                                                       anime_init = browser.OtakuBrowser().get_anime_init(actionArgs.get('anilist_id'), filter_lang=None)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\OtakuBrowser.py", line 140, in get_anime_init
                                                       return self.get_anime_trakt(anilist_id, filter_lang=filter_lang)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\OtakuBrowser.py", line 103, in get_anime_trakt
                                                       anime = trakt.TRAKTAPI().get_anime(anilist_id, db_correction)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\indexers\trakt.py", line 229, in get_anime
                                                       return self.get_trakt_seasons(anilist_id, meta_ids, kodi_meta, db_correction)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\indexers\trakt.py", line 212, in get_trakt_seasons
                                                       return target(anilist_id, meta_ids, kodi_meta, url)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\indexers\trakt.py", line 104, in _process_direct_season_view
                                                       result = self._json_request(url)
                                                     File "C:\K19portable\portable_data\addons\plugin.video.otaku\resources\lib\indexers\trakt.py", line 24, in _json_request
                                                       response = json.loads(response)
                                                     File "C:\K19portable\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\K19portable\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\K19portable\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2022-10-07 09:57:20.980 T:9948     INFO <general>: Python interpreter stopped
2022-10-07 09:57:20.993 T:2288    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.otaku/play_movie/21519/1/]
2022-10-07 09:57:20.993 T:2288     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY

I verified there are sources on Nyaa through Fen, so I know it's not a lack of sources available:
![nyaa](https://user-images.githubusercontent.com/13154733/194573647-5ad77747-8efe-4c8d-b631-2ab4968ef61f.png)

**Comment by Goldenfreddy0703** [comment]
Hey just making sure but did you do all the troubleshooting steps as well?

**Comment by Goldenfreddy0703** [comment]
Actually I see the problem now.

**Comment by Goldenfreddy0703** [comment]
Hey @meesterexx , we just made a release today that fixes all the scrapping stuff for movies and all, Pls test today and tell us if this fixes your issue.

**Comment by meesterexx** [comment]
That fixed it. Thank you both so much!

**Comment by Goldenfreddy0703** [comment]
Hey anytime!!!
