### ISSUE TITLE
MyAnimeList Error after u reach threshold and do its thing.

### ISSUE THREAD

**Issue by TomieAi** [Goldenfreddy0703/Otaku#218]
```
2024-02-18 02:41:33.363 T:14936   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'my_list_status'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\default.py", line 21, in <module>
                                                       main.Main()
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\main.py", line 2451, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\main.py", line 2301, in PLAY
                                                       player.play_source(link, anilist_id, watchlist_update_episode, _BROWSER.get_episodeList, int(episode),
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\player.py", line 526, in play_source
                                                       watchlistPlayer().handle_player(anilist_id, watchlist_update, build_playlist, episode, filter_lang, skip)
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\player.py", line 107, in handle_player
                                                       self.keepAlive()
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\player.py", line 290, in keepAlive
                                                       _ = self.onWatchedPercent()
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\player.py", line 141, in onWatchedPercent
                                                       self._watchlist_update(self._anilist_id, self._episode)
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\WatchlistIntegration.py", line 198, in watchlist_update_episode
                                                       status = WatchlistFlavor.watchlist_anime_entry_request(anilist_id).get('status', '')
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\WatchlistFlavor\__init__.py", line 52, in watchlist_anime_entry_request
                                                       return WatchlistFlavor.get_update_flavor().get_watchlist_anime_entry(anilist_id)
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\WatchlistFlavor\MyAnimeList.py", line 281, in get_watchlist_anime_entry
                                                       results = json.loads(r)['my_list_status']
                                                   KeyError: 'my_list_status'
                                                   -->End of Python script error report<--
                                                   
                                                   ```

**Comment by Goldenfreddy0703** [comment]
Mal was recently down, you may want to reauthorize mal and clear cache, torrent cache, and rebuilding database. 

Mal usually has problems.

**Comment by TomieAi** [comment]
i just use anilist instead xD they are more candy easy to use for me xD

feel free to close if u think this is just mal acting up.. i did reauth again and again and has the same fate sadly..

**Comment by Goldenfreddy0703** [comment]
Mmm that Is a bit odd, if you did rebuild database, menus, they would show up for mal and all but still. 

Mal wtchlist mostly has problems and all. If you do want to sync your mal watch with anilist, there should be a way to do it. Another easy way is to use simkl cause simkl can sync almost everything you give it and it's amazing.

**Comment by Goldenfreddy0703** [comment]
Hey @TomieAi question, was this on a certain anime and if so could you tell me what that anime is? Its possible that you access an anime that was only on anilist/kitsu sense anilist is weird with there anime and if mal could not detect it, that could be the issues but if you can get back me on this, that would be great. 

Thanks.

**Comment by TomieAi** [comment]
> Hey @TomieAi question, was this on a certain anime and if so could you tell me what that anime is? Its possible that you access an anime that was only on anilist/kitsu sense anilist is weird with there anime and if mal could not detect it, that could be the issues but if you can get back me on this, that would be great.
> 
> Thanks.

ow every single anime it dint work on MAL

## Here a fresh auth account of mal
![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/8a4a4dfe-77b0-4414-8e36-f6e5481be533)
## Here to verify
![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/7cd3022d-e4a6-4961-967c-aa0aa3cd03a9)
![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/466a9b62-e102-4018-8175-6f64a54318fe)
## Lets test a random anime from category "Trending from Last Year"
![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/3dd032f0-dc2d-4448-9f1c-76f2151f1e90)
## when threshold hit
![image](https://github.com/Goldenfreddy0703/Otaku/assets/111332073/8555a5eb-939b-4353-8ca0-008dab9768b9)
## the log says this again
```
2024-02-18 02:41:33.363 T:14936   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'my_list_status'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\default.py", line 21, in <module>
                                                       main.Main()
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\main.py", line 2451, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\main.py", line 2301, in PLAY
                                                       player.play_source(link, anilist_id, watchlist_update_episode, _BROWSER.get_episodeList, int(episode),
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\player.py", line 526, in play_source
                                                       watchlistPlayer().handle_player(anilist_id, watchlist_update, build_playlist, episode, filter_lang, skip)
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\player.py", line 107, in handle_player
                                                       self.keepAlive()
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\player.py", line 290, in keepAlive
                                                       _ = self.onWatchedPercent()
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\player.py", line 141, in onWatchedPercent
                                                       self._watchlist_update(self._anilist_id, self._episode)
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\WatchlistIntegration.py", line 198, in watchlist_update_episode
                                                       status = WatchlistFlavor.watchlist_anime_entry_request(anilist_id).get('status', '')
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\WatchlistFlavor\__init__.py", line 52, in watchlist_anime_entry_request
                                                       return WatchlistFlavor.get_update_flavor().get_watchlist_anime_entry(anilist_id)
                                                     File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\WatchlistFlavor\MyAnimeList.py", line 281, in get_watchlist_anime_entry
                                                       results = json.loads(r)['my_list_status']
                                                   KeyError: 'my_list_status'
                                                   -->End of Python script error report<--
                                                   
                                                   ```
                                                   ```

**Comment by Goldenfreddy0703** [comment]
Ok odd thx for showing.

**Comment by Goldenfreddy0703** [comment]
Hey so I should have asked this from the beginning cause it's possible you maybe using an apple device or Xbox. 

What device and kodi version are you using? I tried replicating the issue but had no luck.

**Comment by TomieAi** [comment]
> Hey so I should have asked this from the beginning cause it's possible you maybe using an apple device or Xbox.
> 
> What device and kodi version are you using? I tried replicating the issue but had no luck.

kodi from windows app store.

**Comment by Goldenfreddy0703** [comment]
That's very surprising, first time hearing someone use kodi from the windows app store. Thx

**Comment by Goldenfreddy0703** [comment]
Ok i tried to reproduce the issue but i give up. I think it has something todo with your end, my best solution at this point is to either reinstall Otaku and have its appdata cleared or reinstalling kodi at this point. 

Mal is always weird and idk why but im gonna go ahead and close this issues sense your using anilist. If you do want a watchlist that is close to mal, there is always simkl sense simkl has the same data mal does and you can integrate your mal watchlist with it. Hope this helps and sorry we could not figure it out. 

Thank you.
