### ISSUE TITLE
Otaku will not open in 18.9

### ISSUE THREAD

**Issue by iMikeHimself** [Goldenfreddy0703/Otaku#22]
2022-10-08 14:46:31.370 T:18260   ERROR: Unable to find plugin
2022-10-08 14:46:31.370 T:18260   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://
2022-10-08 14:46:31.370 T:23340   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
2022-10-08 14:46:34.806 T:23340   ERROR: Control 52 in window 10025 has been asked to focus, but it can't
2022-10-08 14:46:35.022 T:23164   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: Non-ASCII character '\xc3' in file C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\pages\nyaa.py on line 259, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (nyaa.py, line 259)
                                            Traceback (most recent call last):
                                              File "C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.otaku\default.py", line 3, in <module>
                                                from resources.lib.OtakuBrowser import OtakuBrowser
                                              File "C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\OtakuBrowser.py", line 4, in <module>
                                                from resources.lib import pages
                                              File "C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\pages\__init__.py", line 2, in <module>
                                                from resources.lib.pages import nyaa, gogoanime, animixplay, debrid_cloudfiles
                                              File "C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\pages\nyaa.py", line 259
                                            SyntaxError: Non-ASCII character '\xc3' in file C:\Users\Mick\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\pages\nyaa.py on line 259, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
                                            -->End of Python script error report<--
2022-10-08 14:46:35.083 T:21236   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.otaku/
2022-10-08 14:46:35.086 T:23340   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/) failed
2022-10-08 14:46:44.079 T:28364   ERROR: AddOnLog: Joystick Support: JOYSTICK::CJoystickInterfaceDirectInput::EnumJoysticksCallback: Failed to SetCooperativeLevel on: J

**Comment by Goldenfreddy0703** [comment]
Hey @iMikeHimself we just released a fix that fixes Otaku for 18.9, test today or tomorrow and tell us if this fixes your issue.

**Comment by Goldenfreddy0703** [comment]
Hey so sense you messaged me on reddit that its working, im going to go ahead and close this issue but thank you for testing and glad we fixed your issue.
