### ISSUE TITLE
Playback won't start on Kodi 18.9

### ISSUE THREAD

**Issue by matteogarzon** [Goldenfreddy0703/Otaku#248]
I'm running Kodi 18.9 installed through Cydia on an iPad Mini (32-bit device).
The extension works, but the playback of both movies and tv shows won't begin, and Kodi just says "Check log for more information".
I tried changing the providers, the max. resolution to 720p, and hided hevc items too (just in case).

```log
2024-04-28 19:58:06.131 T:526553088 WARNING: DARWINIOS: underflow (0 vs 8192 bytes)
2024-04-28 19:58:25.266 T:523358208   ERROR: Traceback (most recent call last):
2024-04-28 19:58:25.267 T:523358208   ERROR:   File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/resources/lib/ui/database.py", line 602, in _update_episode
2024-04-28 19:58:25.273 T:523358208   ERROR:     (show_id, season, kodi_meta, update_time, number, number_abs, air_date))
2024-04-28 19:58:25.273 T:523358208   ERROR: ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
2024-04-28 19:58:34.536 T:523358208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe1' in position 68: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/default.py", line 21, in <module>
                                                main.Main()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2535, in Main
                                                router_process(control.get_plugin_url(), control.get_plugin_params())
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                return route_obj.func(payload, params)
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2291, in PLAY
                                                sources = _BROWSER.get_sources(anilist_id, episode, filter_lang, 'show', rescrape, source_select)
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/resources/lib/OtakuBrowser.py", line 219, in get_sources
                                                control.setSetting("torrent.query.data", str(query))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 68: ordinal not in range(128)
                                            -->End of Python script error report<--
2024-04-28 19:58:34.587 T:526020608  NOTICE: void CAAudioUnitSink::setCoreAudioPreferredSampleRate() requesting hw samplerate 44100.000000
2024-04-28 19:58:34.594 T:526020608  NOTICE: void CAAudioUnitSink::setCoreAudioBuffersize() setting buffer duration to 0.023220
2024-04-28 19:58:34.617 T:526020608  NOTICE: bool CAAudioUnitSink::setupAudio() setup audio format: [lpcm] Mixable Interleaved 2 Channel 32-bit Floating Point LE (44100Hz)
2024-04-28 19:58:34.829 T:522293248   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.otaku/play/154587/8/]
2024-04-28 19:58:41.340 T:523358208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe1' in position 68: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/default.py", line 21, in <module>
                                                main.Main()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2535, in Main
                                                router_process(control.get_plugin_url(), control.get_plugin_params())
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                return route_obj.func(payload, params)
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2291, in PLAY
                                                sources = _BROWSER.get_sources(anilist_id, episode, filter_lang, 'show', rescrape, source_select)
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.otaku/resources/lib/OtakuBrowser.py", line 219, in get_sources
                                                control.setSetting("torrent.query.data", str(query))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 68: ordinal not in range(128)
                                            -->End of Python script error report<--
2024-04-28 19:58:41.592 T:522293248   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.otaku/play/154587/8/]
2024-04-28 19:59:31.750 T:526553088 WARNING: DARWINIOS: underflow (0 vs 8192 bytes)
```

Thank you in advance!

**Comment by Goldenfreddy0703** [comment]
Hey there, thanks for posting a log. From looking at your log, I can see your using an Apple Device and kodi on apple devices always have many bugs, yours seems to be a rare bug though sense your using 18.9 on an iPad Mini. @Gujal00 may want to look into this very soon so we will see if we can look into this. 

Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so looks like our scrapping improvements has causes the issue so that was my bad, our latest update should have this fixed so we should be good but just incase, give it a test whenever you can for us and we can close this issue.

Thank you

**Comment by matteogarzon** [comment]
It worked!! Thank you so much!!!

For some reason, Kodi didn't see the update and even removing and adding again the repository and extension didn't work (most probably a Kodi bug, lol)
The trick was to delete everything otaku related from Filza, and then reinstall the repository and the extension.
