### ISSUE TITLE
Watchlist Kitsu  gives an error

### ISSUE THREAD

**Issue by giventofly** [Goldenfreddy0703/Otaku#250]
I noticed the episodes I watch are not getting updated and if I do the watchlist manual update also gives an error, details:

```
2024-05-01 19:59:04.061 T:2251    error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-05-01 19:59:09.528 T:6143    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/userdata/system/.kodi/addons/plugin.video.otaku/default.py", line 21, in <module>
                                                       main.Main()
                                                     File "/userdata/system/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2531, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "/userdata/system/.kodi/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/userdata/system/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2358, in MARKED_AS_WATCHED
                                                       watchlist_update_episode(anilist_id, episode)
                                                     File "/userdata/system/.kodi/addons/plugin.video.otaku/resources/lib/WatchlistIntegration.py", line 201, in watchlist_update_episode
                                                       return WatchlistFlavor.watchlist_update_episdoe(anilist_id, episode)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/userdata/system/.kodi/addons/plugin.video.otaku/resources/lib/WatchlistFlavor/__init__.py", line 120, in watchlist_update_episdoe
                                                       return WatchlistFlavor.get_update_flavor().update_num_episodes(anilist_id, episode)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/userdata/system/.kodi/addons/plugin.video.otaku/resources/lib/WatchlistFlavor/Kitsu.py", line 340, in update_num_episodes
                                                       kitsu_id = self._get_mapping_id(anilist_id, 'kitsu_id')
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/userdata/system/.kodi/addons/plugin.video.otaku/resources/lib/WatchlistFlavor/WatchlistFlavorBase.py", line 81, in _get_mapping_id
                                                       mapping_id = show[flavor] if show and show.get(flavor) else self._get_flavor_id(anilist_id, flavor)
                                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/userdata/system/.kodi/addons/plugin.video.otaku/resources/lib/WatchlistFlavor/WatchlistFlavorBase.py", line 87, in _get_flavor_id
                                                       if anime_ids.get(flavor):
                                                          ^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error 
```

It happens when seeing an episodes from my kitsu list and also when trying to update manually

**Comment by Goldenfreddy0703** [comment]
Kitsu is always causing issues for some odd reason, we are unsure why but we may have to redo Kitsu and follow there new api.

**Comment by giventofly** [comment]
So currently the solution is to update manually ?

**Comment by theasguard** [comment]
> So currently the solution is to update manually ?

use anilist, simkl or mal for right now, i believe you can sync your watchlist to simkl on their site.
or setup malsync and sync your lists that way. 
sorry if this doesnt help you, just thought id offer some suggestions

**Comment by giventofly** [comment]
I think I tried to set up https://myanimelist.net/ on otaku and it gave an error, so I tried next with otaku and stick with it.

will try again with one of those, thanks

**Comment by Gujal00** [comment]
> I noticed the episodes I watch are not getting updated and if I do the watchlist manual update also gives an error, details:
> 
> It happens when seeing an episodes from my kitsu list and also when trying to update manually

Is it happening on a particular anime or any title.

**Comment by Goldenfreddy0703** [comment]
> Is it happening on a particular anime or any title.

Hey, sorry I never responded sooner but its possible that it could be happening on any title cause kitsu follows the anilist database so basically kitsu is basically a mix of anilist and mal which is why I think it could be happening to any title.

**Comment by giventofly** [comment]
It was happening on all titles, I tested now because I saw there was an addon update (did the update) and seems that currently it is working - I didn't check the changelog, but or it was fixed or it was a coincidence.

I think I will give it a try to a different one based on the suggestion I received here.
