### ISSUE TITLE
Can't watch newly released anime

### ISSUE THREAD

**Issue by Oose97** [Goldenfreddy0703/Otaku#290]
Tried to watch newly released anime like suicide squad or code geass, but otaku keeps throwing error when I try to load episodes list. It works fine if I try to watch anime from this season. Tried all steps described in "Troubleshooting tips". Using it in kodi for android TV.

Error log:
```
2024-06-27 16:38:45.854 T:7070    error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-06-27 16:39:04.074 T:12274   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/default.py", line 21, in <module>
                                                       main.Main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2557, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/WatchlistIntegration.py", line 67, in WATCHLIST_TO_EP
                                                       anime_general, content_type = OtakuBrowser().get_anime_init(anilist_id)
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/OtakuBrowser.py", line 105, in get_anime_init
                                                       data = simkl.SIMKLAPI().get_episodes(anilist_id, filter_lang)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 183, in get_episodes
                                                       return self._process_episode_view(anilist_id, poster, fanart, eps_watched, tvshowtitle, filter_lang,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/indexers/simkl.py", line 100, in _process_episode_view
                                                       s_id = utils.get_season(sync_data[0]) if sync_data else None
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/utils.py", line 94, in get_season
                                                       if isinstance(res.get('title'), dict):
                                                                     ^^^^^^^
                                                   AttributeError: 'str' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2024-06-27 16:39:04.325 T:12273   error <general>: GetDirectory - Error getting plugin://plugin.video.otaku/watchlist_to_ep/166710/55848//3
2024-06-27 16:39:04.328 T:7070    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/watchlist_to_ep/166710/55848//3) failed
2024-06-27 16:39:22.344 T:7070     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-06-27 16:39:27.794 T:12292   error <general>: GetDirectory - Error getting plugin://plugin.video.otaku/wipe_addon_data
2024-06-27 16:39:27.811 T:7070    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/wipe_addon_data) failed
2024-06-27 16:39:34.560 T:12305   error <general>: GetDirectory - Error getting plugin://plugin.video.otaku/rebuild_database
2024-06-27 16:39:34.562 T:7070    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/rebuild_database) failed
2024-06-27 16:39:40.875 T:12318   error <general>: GetDirectory - Error getting plugin://plugin.video.otaku/clear_cache
2024-06-27 16:39:40.878 T:7070    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/clear_cache) failed
2024-06-27 16:39:44.130 T:12225 warning <general>: Repository add-on repository.elementumorg uses plain HTTP for add-on downloads in path http://127.0.0.1:65223/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-06-27 16:39:45.325 T:7070     info <general>: Skipped 2 duplicate messages..
2024-06-27 16:39:45.325 T:7070    error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-06-27 16:39:50.450 T:7070     info <general>: Samba is idle. Closing the remaining connections
2024-06-27 16:39:51.392 T:12349   error <general>: Traceback (most recent call last):
                                                   
2024-06-27 16:39:51.392 T:12349   error <general>: 
2024-06-27 16:39:51.395 T:12349   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/database.py", line 58, in get
                                                       data = ast.literal_eval(fresh_result)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.396 T:12349   error <general>: 
2024-06-27 16:39:51.396 T:12349   error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ast.py", line 64, in literal_eval
                                                       node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.396 T:12349   error <general>: 
2024-06-27 16:39:51.396 T:12349   error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ast.py", line 50, in parse
                                                       return compile(source, filename, mode, flags,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.396 T:12349   error <general>: 
2024-06-27 16:39:51.396 T:12349   error <general>: SystemError: AST constructor recursion depth mismatch (before=27, after=21)
                                                   
2024-06-27 16:39:51.396 T:12349   error <general>: 
2024-06-27 16:39:51.401 T:12348   error <general>: Traceback (most recent call last):
                                                   
2024-06-27 16:39:51.402 T:12348   error <general>: 
2024-06-27 16:39:51.402 T:12348   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/database.py", line 58, in get
                                                       data = ast.literal_eval(fresh_result)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.402 T:12348   error <general>: 
2024-06-27 16:39:51.403 T:12348   error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ast.py", line 64, in literal_eval
                                                       node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.403 T:12348   error <general>: 
2024-06-27 16:39:51.403 T:12348   error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ast.py", line 50, in parse
                                                       return compile(source, filename, mode, flags,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.403 T:12348   error <general>: 
2024-06-27 16:39:51.403 T:12348   error <general>: SystemError: AST constructor recursion depth mismatch (before=27, after=30)
                                                   
2024-06-27 16:39:51.403 T:12348   error <general>: 
2024-06-27 16:39:51.458 T:12347   error <general>: Traceback (most recent call last):
                                                   
2024-06-27 16:39:51.458 T:12347   error <general>: 
2024-06-27 16:39:51.459 T:12347   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/database.py", line 58, in get
                                                       data = ast.literal_eval(fresh_result)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.459 T:12347   error <general>: 
2024-06-27 16:39:51.459 T:12347   error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ast.py", line 64, in literal_eval
                                                       node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.460 T:12347   error <general>: 
2024-06-27 16:39:51.461 T:12347   error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ast.py", line 50, in parse
                                                       return compile(source, filename, mode, flags,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.461 T:12347   error <general>: 
2024-06-27 16:39:51.461 T:12347   error <general>: SystemError: AST constructor recursion depth mismatch (before=27, after=21)
                                                   
2024-06-27 16:39:51.461 T:12347   error <general>: 
2024-06-27 16:39:51.662 T:12346   error <general>: Traceback (most recent call last):
                                                   
2024-06-27 16:39:51.662 T:12346   error <general>: 
2024-06-27 16:39:51.663 T:12346   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/database.py", line 58, in get
                                                       data = ast.literal_eval(fresh_result)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.663 T:12346   error <general>: 
2024-06-27 16:39:51.663 T:12346   error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ast.py", line 64, in literal_eval
                                                       node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.663 T:12346   error <general>: 
2024-06-27 16:39:51.663 T:12346   error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ast.py", line 50, in parse
                                                       return compile(source, filename, mode, flags,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.663 T:12346   error <general>: 
2024-06-27 16:39:51.663 T:12346   error <general>: SystemError: AST constructor recursion depth mismatch (before=27, after=30)
                                                   
2024-06-27 16:39:51.663 T:12346   error <general>: 
2024-06-27 16:39:51.778 T:12347   error <general>: Traceback (most recent call last):
                                                   
2024-06-27 16:39:51.779 T:12347   error <general>: 
2024-06-27 16:39:51.780 T:12347   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/database.py", line 58, in get
                                                       data = ast.literal_eval(fresh_result)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.780 T:12347   error <general>: 
2024-06-27 16:39:51.780 T:12347   error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ast.py", line 64, in literal_eval
                                                       node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.780 T:12347   error <general>: 
2024-06-27 16:39:51.780 T:12347   error <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/ast.py", line 50, in parse
                                                       return compile(source, filename, mode, flags,
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-06-27 16:39:51.780 T:12347   error <general>: 
2024-06-27 16:39:51.780 T:12347   error <general>: SystemError: AST constructor recursion depth mismatch (before=27, after=31)
```

**Comment by Goldenfreddy0703** [comment]
Hey small question what version of Kodi are you using and what device? My guess is that it's either an ipv6 error when you would have to disable on your device or you may need to unplug and plug your router back in.

Reason why I think that is cause it was working fine in the past so could have something todo with that.

**Comment by Oose97** [comment]
Kodi info:
![20240628_125608.jpg](https://github.com/Goldenfreddy0703/Otaku/assets/147850885/61a1e5d9-0998-431d-ac78-add89b10742f)
Device i'm using - philips 55oled806
Changed ip settings to not have ipv6, still same issue. Same thing after restarting router. Tv was also restarted by plugging it off.

**Comment by Gujal00** [comment]
Provide full unedited DEBUG log, no use with snippets as it is not possible to see which path it took to reach that error

**Comment by Goldenfreddy0703** [comment]
Hey so a change had to be reverted and released so try out our latest version and see if this fixes your issue. 

Thank you

**Comment by Oose97** [comment]
It did, thanks.
