### ISSUE TITLE
Otaku Wont Load

### ISSUE THREAD

**Issue by Timewarrener** [Goldenfreddy0703/Otaku#315]
This is the error received in the log
looks like Ciarands change the URL about 30mins ago from this post. 

https://raw.githubusercontent.com/Ciarands/vidsrc-keys/main/keys.json

```
2024-08-09 15:34:22.765 T:89544    info <general>: @@@@Otaku log:
                                                   Request-Error: (local variable 'response' referenced before assignment) => https://raw.githubusercontent.com/Ciarands/keys/main/keys.json
2024-08-09 15:34:22.767 T:89544   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: the JSON object must be str, bytes or bytearray, not NoneType
                                                   Traceback (most recent call last):
                                                     File "C:\Users\timewarrener\AppData\Roaming\Kodi\addons\plugin.video.otaku\service.py", line 8, in <module>
                                                       maintenance.run_maintenance()
                                                     File "C:\Users\timewarrener\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\maintenance.py", line 92, in run_maintenance
                                                       get_keys()
                                                     File "C:\Users\timewarrener\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\ui\maintenance.py", line 74, in get_keys
                                                       resp = json.loads(resp)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 341, in loads
                                                       raise TypeError(f'the JSON object must be str, bytes or bytearray, '
                                                   TypeError: the JSON object must be str, bytes or bytearray, not NoneType
                                                   -->End of Python script error report<--
                                                   
2024-08-09 15:34:24.342 T:87996    info <general>: Loading controller layout: C:\Program Files\Kodi\addons\game.controller.keyboard\resources\layout.xml
2024-08-09 15:34:26.259 T:90164    info <general>: CIRServerSuite::Process: failed to connect to irss, will keep retrying every 5 seconds
2024-08-09 15:34:26.541 T:87996    info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2024-08-09 15:34:26.666 T:70244   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\timewarrener\AppData\Roaming\Kodi\addons\plugin.video.otaku\default.py", line 19, in <module>
                                                       from resources.lib import main
                                                     File "C:\Users\timewarrener\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\main.py", line 26, in <module>
                                                       from resources.lib.OtakuBrowser import OtakuBrowser
                                                     File "C:\Users\timewarrener\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\OtakuBrowser.py", line 6, in <module>
                                                       from resources.lib import pages
                                                     File "C:\Users\timewarrener\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\pages\__init__.py", line 4, in <module>
                                                       from resources.lib.pages import nyaa, animetosho, animixplay, debrid_cloudfiles, \
                                                     File "C:\Users\timewarrener\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\pages\aniwave.py", line 14, in <module>
                                                       class sources(BrowserBase):
                                                     File "C:\Users\timewarrener\AppData\Roaming\Kodi\addons\plugin.video.otaku\resources\lib\pages\aniwave.py", line 16, in sources
                                                       EKEY, DKEY = json.loads(control.getSetting('keys.aniwave'))
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2024-08-09 15:34:26.685 T:86232   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.otaku/
2024-08-09 15:34:26.691 T:87996   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/) failed

```

**Comment by Goldenfreddy0703** [comment]
Hey thanks for pointing this put, will have that url changed on our end as well and release in a few min. Thanks

**Comment by Goldenfreddy0703** [comment]
Ok release should be out that should hopefully fix this, the output as well changed to needed to update it and all. @Gujal00 if you have time, see if you can look into this very soon. 

Thank you
