### ISSUE TITLE
[BUG]popup bug after reboot

### ISSUE THREAD

**Issue by epidoma** [Goldenfreddy0703/Otaku#326]
Hi
After every reboot i get in top right corner otaku error check log for more info...
so here is otaku part from log
2024-08-21 13:15:21.761 T:4115    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'list' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.otaku/service.py", line 8, in <module>
                                                       maintenance.run_maintenance()
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/ui/maintenance.py", line 100, in run_maintenance
                                                       get_keys()
                                                     File "/storage/.kodi/addons/plugin.video.otaku/resources/lib/ui/maintenance.py", line 79, in get_keys
                                                       vidplay = resp.get('embed.js')
                                                                 ^^^^^^^^
                                                   AttributeError: 'list' object has no attribute 'get'
                                                   -->End of Python script error report<--

[kodi.log](https://github.com/user-attachments/files/16690756/kodi.log)

**Comment by Hemicrusher** [comment]
I am getting the same error at startup.

**Comment by Goldenfreddy0703** [comment]
Hey so this is an error with one of our embeds due to a specific website developer that changes the logic weekly, Hopefully this will be fixed very soon. Are you guys able to still use Otaku?

**Comment by Hemicrusher** [comment]
> Hey so this is an error with one of our embeds due to a specific website developer that changes the logic weekly, Hopefully this will be fixed very soon. Are you guys able to still use Otaku?

Yeah, it still works. But this other issue happened when I saw the error.  A show I am watching and tracking with Kitsu, showed all episodes I watched, as watched. Now the first 8 or so show as unwatched, and the next five show as watched. I then watched another episode and it showed watched in Kitsu, but the first 8 still show as unwatched, so it seems to be tracking new watched episodes.  So, not sure if this is a Kitsu issue or Otaku...

Thanks!

**Comment by kay-ama** [comment]
hey just wanted to drop in and say i wasn’t able to get Otaku to even work without this error popping up. Going to reinstall it and see if it fixes.

**Comment by Goldenfreddy0703** [comment]
What device are you using?

**Comment by kay-ama** [comment]
Fire Stick TV 4k, to be specific. I’m updating it right now to see if that’s the problem but here’s the error string i’m getting from the log. (After the updates it still didn’t work)

![image](https://github.com/user-attachments/assets/83bffe3a-5524-41d3-8c74-1f06f8ca9863)

**Comment by Goldenfreddy0703** [comment]
On weird so it's basically half working

**Comment by Hemicrusher** [comment]
> most likely a kitsu issue, kitsu has always had issues with watchlist which is quite weird.

I want to use MAL for tracking, but I am using an AndroidTV box, and tried using Yatse to past the URL but keep getting a login error, even after verifying the string is correct. 

I really wish Otaku used the MAL login like AnimeTV for Android does. So, I have been using Kitsu...but might go back to Simkl, except I need to pay to get English titles, which is why I use Kitsu.

Thanks for all your work!

**Comment by Goldenfreddy0703** [comment]
Wait you have to pay to get English titles? That's quite dumb

**Comment by Goldenfreddy0703** [comment]
Ok maybe in the future, I will add that import and export settings very soon. Just haven't been working on Otaku for a few weeks.b
