### ISSUE TITLE
Can't play any episode, crashes.

### ISSUE THREAD

**Issue by RhanCandia** [Goldenfreddy0703/Otaku#335]
I'm the Steam Deck if that matters. Installed Kodi via Flathub.

Here's the log that stood out.

```
2024-09-18 15:26:15.011 T:107     debug <general>: Thread Timer 140713041843904 terminating
2024-09-18 15:26:15.020 T:7       debug <general>: CGLContextEGL::SwapBuffers: sync check blocking
2024-09-18 15:26:15.027 T:7       debug <general>: CGLContextEGL::SwapBuffers: sync sleep: 6344
2024-09-18 15:26:16.388 T:98      debug <general>: [script.module.inputstreamhelper] Platform information: uname_result(system='Linux', node='steamdeck', release='6.1.52-valve16-1-neptune-61', version='#1 SMP PREEMPT_DYNAMIC Tue, 06 Feb 2024 00:51:49 +0000', machine='x86_64')
2024-09-18 15:26:16.389 T:98      debug <CAddonSettings[0@script.module.inputstreamhelper]>: trying to load setting definitions from old format...
**2024-09-18 15:26:16.390 T:98      debug <general>: [script.module.inputstreamhelper] inputstream.adaptive is installed.
2024-09-18 15:26:16.390 T:98      debug <general>: [script.module.inputstreamhelper] inputstream.adaptive 21.5.2 is enabled.
2024-09-18 15:26:16.390 T:98      debug <general>: [script.module.inputstreamhelper] inputstream.adaptive 21.5.2 is installed and enabled.
2024-09-18 15:26:16.512 T:98      error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>=' not supported between instances of 'LooseVersion' and 'Version'
                                                   Traceback (most recent call last):
                                                     File "/home/deck/.var/app/tv.kodi.Kodi/data/addons/plugin.video.otaku/default.py", line 21, in <module>
                                                       main.Main()
                                                     File "/home/deck/.var/app/tv.kodi.Kodi/data/addons/plugin.video.otaku/resources/lib/main.py", line 2631, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "/home/deck/.var/app/tv.kodi.Kodi/data/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/deck/.var/app/tv.kodi.Kodi/data/addons/plugin.video.otaku/resources/lib/main.py", line 2339, in PLAY
                                                       player.play_source(link, anilist_id, watchlist_update_episode, _BROWSER.get_episodeList, int(episode),
                                                     File "/home/deck/.var/app/tv.kodi.Kodi/data/addons/plugin.video.otaku/resources/lib/ui/player.py", line 566, in play_source
                                                       item = hook_mimetype.trigger(linkInfo['headers']['Content-Type'], item)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/deck/.var/app/tv.kodi.Kodi/data/addons/plugin.video.otaku/resources/lib/ui/player.py", line 23, in trigger
                                                       return cls.__MIME_HOOKS[mimetype](item)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/deck/.var/app/tv.kodi.Kodi/data/addons/plugin.video.otaku/resources/lib/ui/player.py", line 611, in _HLS_HOOK
                                                       if is_helper.check_inputstream():
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/deck/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 434, in check_inputstream
                                                       if self.protocol == 'hls' and not self._supports_hls():
                                                                                         ^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/deck/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 376, in _supports_hls
                                                       if parse_version(self._inputstream_version()) >= parse_version(config.HLS_MINIMUM_IA_VERSION):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '>=' not supported between instances of 'LooseVersion' and 'Version'
                                                   -->End of Python script error report<--**
                                                   
2024-09-18 15:26:16.512 T:98      debug <general>: onExecutionDone(9, /home/deck/.var/app/tv.kodi.Kodi/data/addons/plugin.video.otaku/default.py)
2024-09-18 15:26:16.528 T:98      debug <general>: .
2024-09-18 15:26:16.530 T:7       debug <general>: ------ Window Init (DialogNotification.xml) ------
2024-09-18 15:26:16.578 T:7       debug <general>: CGLContextEGL::SwapBuffers: sync check blocking
2024-09-18 15:26:16.585 T:7       debug <general>: CGLContextEGL::SwapBuffers: sync sleep: 6277
2024-09-18 15:26:16.587 T:98      debug <general>: Python interpreter stopped
2024-09-18 15:26:16.587 T:98      debug <general>: Thread LanguageInvoker 140713782138560 terminating
2024-09-18 15:26:16.606 T:99      debug <general>: Thread ScriptObs 140713025251008 terminating
2024-09-18 15:26:16.610 T:7       error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.otaku/play/145665/5/]
2024-09-18 15:26:16.610 T:7       debug <general>: Playlist Player: no more playable items... aborting playback
2024-09-18 15:26:16.610 T:108     debug <general>: Thread BackgroundLoader start, auto delete: false
2024-09-18 15:26:16.610 T:7       debug <general>: [threads] name: 'BackgroundLoader' priority: '1'
2024-09-18 15:26:16.614 T:108     debug <general>: Thread BackgroundLoader 140713050236608 terminating
2024-09-18 15:26:18.335 T:7       debug <general>: Keyboard: scancode: 0x9, sym: 0x1b, unicode: 0x1b, modifier: 0x0
2024-09-18 15:26:18.427 T:7       debug <general>: Keyboard: scancode: 0x9, sym: 0x1b, unicode: 0x00, modifier: 0x0
2024-09-18 15:26:18.427 T:7       debug <general>: HandleKey: escape (0xf01b) pressed, window 10025, action is PreviousMenu
2024-09-18 15:26:18.427 T:7       debug <general>: CGUIWindowManager::PreviousWindow: Deactivate
2024-09-18 15:26:18.737 T:7       debug <general>: ------ Window Deinit (MyVideoNav.xml) ------
2024-09-18 15:26:18.737 T:7       debug <general>: FreeVisualisation() done
2024-09-18 15:26:18.743 T:7       debug <general>: CGUIWindowManager::PreviousWindow: Activate new
2024-09-18 15:26:18.743 T:7       debug <general>: ------ Window Init (Custom_1100_AddonLauncher.xml) ------
2024-09-18 15:26:18.744 T:7       debug <general>: CDirectoryProvider[addons://sources/video/]: refreshing..
2024-09-18 15:26:18.744 T:7       debug <general>: CDirectoryProvider[addons://sources/audio/]: refreshing..
2024-09-18 15:26:18.744 T:7       debug <general>: CDirectoryProvider[addons://sources/game/]: refreshing..
2024-09-18 15:26:18.744 T:7       debug <general>: CDirectoryProvider[addons://sources/executable/]: refreshing..
2024-09-18 15:26:18.744 T:7       debug <general>: CDirectoryProvider[addons://sources/image/]: refreshing..
2024-09-18 15:26:18.744 T:7       debug <general>: CDirectoryProvider[addons://all/]: refreshing..
2024-09-18 15:26:18.744 T:7       debug <general>: CDirectoryProvider[addons://user]: refreshing..
2024-09-18 15:26:18.744 T:7       debug <general>: CDirectoryProvider[addons://outdated/]: refreshing..
2024-09-18 15:26:18.746 T:79      debug <general>: CAddonDatabase: SELECT repo.id FROM repo .. took 0 ms
2024-09-18 15:26:18.752 T:79       info <general>: Skipped 1 duplicate messages..
2024-09-18 15:26:18.752 T:79      debug <general>: CAddonDatabase: query  SELECT addons.*, repo.addonID AS repoID FROM addons JOIN addonlinkrepo ON addons.id=addonlinkrepo.idAddon JOIN repo ON repo.id=addonlinkrepo.idRepo WHERE addonlinkrepo.idRepo IN (1,2,3) ORDER BY repo.addonID, addons.addonID returned 826 rows in 5 ms
2024-09-18 15:26:18.754 T:79      error <general>: Repository add-on repository.atreides.tools uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-09-18 15:26:18.754 T:79      error <general>: Repository add-on repository.atreides.tools does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-09-18 15:26:18.755 T:79      error <general>: Repository add-on repository.universalscrapers uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-09-18 15:26:18.755 T:79      error <general>: Repository add-on repository.universalscrapers does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-09-18 15:26:18.755 T:81      debug <general>: CAddonDatabase: query  SELECT addons.*, repo.addonID AS repoID FROM addons JOIN addonlinkrepo ON addons.id=addonlinkrepo.idAddon JOIN repo ON repo.id=addonlinkrepo.idRepo WHERE addonlinkrepo.idRepo IN (1,2,3) ORDER BY repo.addonID, addons.addonID returned 826 rows in 6 ms
2024-09-18 15:26:18.758 T:81      error <general>: Repository add-on repository.atreides.tools uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-09-18 15:26:18.758 T:81      error <general>: Repository add-on repository.atreides.tools does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-09-18 15:26:18.759 T:81      error <general>: Repository add-on repository.universalscrapers uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-09-18 15:26:18.759 T:81      error <general>: Repository add-on repository.universalscrapers does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-09-18 15:26:18.785 T:79      debug <general>: CAddonDatabase::GetAddons took 38 ms
2024-09-18 15:26:18.797 T:81      debug <general>: CAddonDatabase::GetAddons took 47 ms
2024-09-18 15:26:18.800 T:81      debug <general>: CAddonMgr::GetAvailableUpdatesOrOutdatedAddons took 51 ms
2024-09-18 15:26:18.806 T:81      debug <general>: CAddonDatabase: SELECT repo.id FROM repo .. took 0 ms
2024-09-18 15:26:18.811 T:81      debug <general>: CAddonDatabase: query  SELECT addons.*, repo.addonID AS repoID FROM addons JOIN addonlinkrepo ON addons.id=addonlinkrepo.idAddon JOIN repo ON repo.id=addonlinkrepo.idRepo WHERE addonlinkrepo.idRepo IN (1,2,3) ORDER BY repo.addonID, addons.addonID returned 826 rows in 4 ms
2024-09-18 15:26:18.813 T:81      error <general>: Repository add-on repository.atreides.tools uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-09-18 15:26:18.813 T:81      error <general>: Repository add-on repository.atreides.tools does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-09-18 15:26:18.814 T:81      error <general>: Repository add-on repository.universalscrapers uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-09-18 15:26:18.814 T:81      error <general>: Repository add-on repository.universalscrapers does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-09-18 15:26:18.843 T:81      debug <general>: CAddonDatabase::GetAddons took 37 ms
2024-09-18 15:26:18.848 T:81      debug <general>: CAddonMgr::GetAddonsWithAvailableUpdate took 42 ms
2024-09-18 15:26:19.443 T:7       debug <general>: Keyboard: scancode: 0x9, sym: 0x1b, unicode: 0x1b, modifier: 0x0
2024-09-18 15:26:19.560 T:7       debug <general>: Keyboard: scancode: 0x9, sym: 0x1b, unicode: 0x00, modifier: 0x0
2024-09-18 15:26:19.560 T:7       debug <general>: HandleKey: escape (0xf01b) pressed, window 11100, action is PreviousMenu
2024-09-18 15:26:19.560 T:7       debug <general>: CGUIWindowManager::PreviousWindow: Deactivate
2024-09-18 15:26:19.861 T:7       debug <general>: ------ Window Deinit (Custom_1100_AddonLauncher.xml) ------
2024-09-18 15:26:19.861 T:7       debug <general>: FreeVisualisation() done
2024-09-18 15:26:19.868 T:7       debug <general>: CGUIWindowManager::PreviousWindow: Activate new
2024-09-18 15:26:19.868 T:7       debug <general>: ------ Window Init (Home.xml) ------
2024-09-18 15:26:19.869 T:7       debug <general>: CDirectoryProvider[addons://]: refreshing..
2024-09-18 15:26:19.869 T:7       debug <general>: CDirectoryProvider[addons://sources/video/]: refreshing..
2024-09-18 15:26:19.869 T:7       debug <general>: CDirectoryProvider[addons://sources/audio/]: refreshing..
2024-09-18 15:26:19.869 T:7       debug <general>: CDirectoryProvider[addons://sources/game/]: refreshing..
2024-09-18 15:26:19.869 T:7       debug <general>: CDirectoryProvider[addons://sources/executable/]: refreshing..
2024-09-18 15:26:19.869 T:7       debug <general>: CDirectoryProvider[addons://sources/image/]: refreshing..
2024-09-18 15:26:19.869 T:7       debug <general>: CDirectoryProvider[addons://sources/game/]: refreshing..
2024-09-18 15:26:19.870 T:82      debug <general>: CAddonDatabase: SELECT repo.id FROM repo .. took 0 ms
2024-09-18 15:26:19.879 T:82      debug <general>: CAddonDatabase: query  SELECT addons.*, repo.addonID AS repoID FROM addons JOIN addonlinkrepo ON addons.id=addonlinkrepo.idAddon JOIN repo ON repo.id=addonlinkrepo.idRepo WHERE addonlinkrepo.idRepo IN (1,2,3) ORDER BY repo.addonID, addons.addonID returned 826 rows in 9 ms
2024-09-18 15:26:19.881 T:82      error <general>: Repository add-on repository.atreides.tools uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-09-18 15:26:19.881 T:82      error <general>: Repository add-on repository.atreides.tools does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition
2024-09-18 15:26:19.882 T:82      error <general>: Repository add-on repository.universalscrapers uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
2024-09-18 15:26:19.882 T:82      error <general>: Repository add-on repository.universalscrapers does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition
```

It was working a few weeks ago. But when I tried it yesterday, that's what I got.

I did the basic trouble shoot. Clear cache, torrent cache, rebuild database. No luck. InputSteam Adaptive seem to be already in the latest version. But the log seem to be complaining something related to that.

I also reinstalled Kodi, made sure to wipe Kodi configs and userdata too.

**Comment by RhanCandia** [comment]
Maybe the the InputStreamHelper addon needs an update.
Might be related to the issue: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/568

**Comment by RhanCandia** [comment]
I went in and modified `/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py`. To force type case the versions being compared. Made them both LooseVersion and that fixed the episode playback.

Maybe this is a StreamImputHelper addon issue so I'll just close this one.

I get to watch episodes again for now after the minor code change.
