### ISSUE TITLE
Getting error trying to check "Get watch order"

### ISSUE THREAD

**Issue by TupeTupeTupeTupe** [Goldenfreddy0703/Otaku#359]
This used to work previously, but suddenly broken. Did cleared cache, wiped addon data, did a full reinstall on this addon.

`2024-11-02 14:39:02.466 T:17689   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/default.py", line 21, in <module>
                                                       main.Main()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 2631, in Main
                                                       router_process(control.get_plugin_url(), control.get_plugin_params())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/router.py", line 70, in router_process
                                                       return route_obj.func(payload, params)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/main.py", line 658, in GET_WATCH_ORDER
                                                       return control.draw_items(_ANILIST_BROWSER.get_watch_order(mal_id))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.otaku/resources/lib/ui/control.py", line 467, in draw_items
                                                       if vid['is_dir']:
                                                          ~~~^^^^^^^^^^
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--`

`2024-11-02 14:39:02.621 T:17688   error <general>: GetDirectory - Error getting plugin://plugin.video.otaku/watch_order//animes/176053/58445/
2024-11-02 14:39:02.629 T:17081   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.otaku/watch_order//animes/176053/58445/) failed`

**Comment by Gujal00** [comment]
The provider site for the `watch order` information seems to be down
`https://chiaki.site/`
Can't do anything in the Otaku addon

**Comment by TupeTupeTupeTupe** [comment]
Oh, thanks for the information. Didn't know that site was used to check information.

Everything else seems to be working for me tho, but thank you so much!

**Comment by jewbmx** [comment]
Dont know if its the same but yall might be able to use jikan or something called animeapi as an alternative. Could be wrong tho, i havent looked at any of it for a while and dont know how the previous results were lol.

**Comment by Goldenfreddy0703** [comment]
Jikan api provides relations, not all anime. Now as for animeapi, I may wanna check that out and @Gujal00 hey, if you don't mind, Otaku testing may need get watch order context menu and I may need your help very soon for Mal browser. Thanks

**Comment by Gujal00** [comment]
`chiaki.site` is back. `Watch order` is back to working in Otaku
